### ISSUE TITLE
Resulting JSON file is empty

### ISSUE THREAD

**Issue by ghost** [gusanmaz/StumbleUponRescuer#2]
Running the command prints out the correct User ID and Like Count, but the resulting `json` file is essentially empty: `{"likes":{"values":[]}}`

**Comment by gusanmaz** [comment]
I haven't tested the tool for accounts that have more than 12K likes. Could you write your account's Like Count? If your like count is below 12K threshold could you also tell your SU username?

**Comment by mpatzer** [comment]
Like count was 352. My username for SU is also `mpatzer`.

**Comment by gusanmaz** [comment]
Is your account private? I couldn't see your likes from your SU page. Making your account public while the tool is running might solve the problem. Could you let me know whether changing your account's privacy solves the issue. If so, I will update readme file accordingly.

**Comment by ghost** [comment]
@gusanmaz That's the issue. Once I change my Likes and Interests under Account Info to "Visible to Everyone", then it works as expected. Thanks for helping me troubleshoot the issue.
